### ISSUE TITLE
[HuggingFace] T5 decoder compilation failed since 2.20.0 sdk

### ISSUE THREAD

**Issue by JingyaHuang** [aws-neuron/aws-neuron-sdk#1013]
Hi team, we met a compilation error while trying to compile the decoder of T5 with Neuron SDK 2.20.0 release. The team has tested that it's working with neuron SDK 2.19.1 release. 

<details close>
<summary>Error Log</summary>
<br>

```
~/optimum-neuron$ optimum-cli export neuron --model t5-small --task text2text-generation --batch_size 1 --sequence_length 18 --num_beams 4 t5_small_neuron/
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.32k/2.32k [00:00<00:00, 28.7MB/s]
spiece.model: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 792k/792k [00:00<00:00, 49.7MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.39M/1.39M [00:00<00:00, 46.7MB/s]
***** Compiling encoder *****
.
Compiler status PASS
[Compilation Time] 22.41 seconds.
***** Compiling decoder *****
/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch_neuronx/xla_impl/hlo_conversion.py:159: UserWarning: Received an input tensor that was unused. Tensor will be ignored. (index=2, shape=torch.Size([4, 18, 512]), dtype=torch.float32)
  warnings.warn(
2024-10-15 12:10:10.000614:  4428  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-10-15 12:10:10.000616:  4428  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/548b184f-a0f3-45d2-a16e-d83a60b3ffe3/model.MODULE_12883270313738124024+d7517139.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/548b184f-a0f3-45d2-a16e-d83a60b3ffe3/model.MODULE_12883270313738124024+d7517139.neff --verbose=35
.
Compiler status PASS
2024-10-15 12:10:12.000475:  4428  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-10-15 12:10:12.000476:  4428  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/30a9830e-0805-4fc8-a2b4-3b32c131a358/model.MODULE_4357995792014989460+d7517139.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/30a9830e-0805-4fc8-a2b4-3b32c131a358/model.MODULE_4357995792014989460+d7517139.neff --verbose=35
.
Compiler status PASS
.root = neuronxcc/starfish/penguin/targets/tonga/TongaISAInst.py
root = neuronxcc/starfish/penguin/targets/tonga
root = neuronxcc/starfish/penguin/targets
root = neuronxcc/starfish/penguin
root = neuronxcc/starfish

[TEN404] (_compare.638) Internal tensorizer error: SundaISel:Invalid BroadcastPartition - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/exporters/neuron/__main__.py", line 725, in <module>
    main()
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/exporters/neuron/__main__.py", line 697, in main
    main_export(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/exporters/neuron/__main__.py", line 587, in main_export
    _, neuron_outputs = export_models(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/exporters/neuron/convert.py", line 366, in export_models
    neuron_inputs, neuron_outputs = export(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/exporters/neuron/convert.py", line 453, in export
    return export_neuronx(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/exporters/neuron/convert.py", line 561, in export_neuronx
    neuron_model = neuronx.trace(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch_neuronx/xla_impl/trace.py", line 574, in trace
    neff_filename, metaneff, flattener, packer, weights = _trace(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch_neuronx/xla_impl/trace.py", line 639, in _trace
    neff_artifacts = generate_neff(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch_neuronx/xla_impl/trace.py", line 492, in generate_neff
    neff_filename = hlo_compile(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/torch_neuronx/xla_impl/trace.py", line 394, in hlo_compile
    raise RuntimeError(f"neuronx-cc failed with {status}")
RuntimeError: neuronx-cc failed with 70
Traceback (most recent call last):
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/commands/optimum_cli.py", line 208, in main
    service.run()
  File "/home/ubuntu/pyvenv/aws_neuron_venv_pytorch/lib/python3.10/site-packages/optimum/commands/export/neuronx.py", line 291, in run
    subprocess.run(full_command, shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 -m optimum.exporters.neuron --model t5-small --task text2text-generation --batch_size 1 --sequence_length 18 --num_beams 4 t5_small_neuron/' returned non-zero exit status 1.
```

</details>

In short:

Used command:
```bash
optimum-cli export neuron --model t5-small --task text2text-generation --batch_size 1 --sequence_length 18 --num_beams 4 t5_small_neuron/
```
and the error:
```
[TEN404] (_compare.638) Internal tensorizer error: SundaISel:Invalid BroadcastPartition - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.
```

Could the team help? Thx!

**Comment by aws-yishanm** [comment]
Hi @JingyaHuang, I am trying to reproduce your issue. Could you tell me what type of neuron instance you ran this command on? Could you also show me the output of ```pip list | grep neuron```? Thanks.

**Comment by aws-yishanm** [comment]
Hi @JingyaHuang, adding the compiler flag `--model-type transformer` will allow the compilation to succeed.

**Comment by JingyaHuang** [comment]
Hi @aws-yishanm, with the flag another error pops up, it seems to be an issue with the gather op this time:

```
[TEN404] (_gather.881) Internal tensorizer error: LegalizeSundaMacro:Incorrect partition ap! - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.
```

My branch for the fix you propose is here: https://github.com/huggingface/optimum-neuron/tree/fix-t5-compilation, only added the flag for T5 decoder since the compilation of the encoder is successful without the flag, did I do anything wrong?

**Comment by aws-yishanm** [comment]
Hi @JingyaHuang, I believe that you may have incorrectly added the compiler flag.

I saw on your branch you used the ```append``` function:

```
    compiler_args.extend(["--optlevel", optlevel])

    compiler_args = add_stable_diffusion_compiler_args(config, compiler_args)  # diffusers specific

    if getattr(config,"is_decoder", False):
        compiler_args.append("--model-type=transformer")
```

where as something like the ```extend``` is what works for me:

```
    compiler_args.extend(["--optlevel", optlevel])

    compiler_args.extend(["--model-type", "transformer"])
```

Also there is no need to only add it to the decoder flag. You can add it to both. Let me know if this works for you!

**Comment by JingyaHuang** [comment]
Hi @aws-yishanm,

I modified the flag as you suggested: https://github.com/huggingface/optimum-neuron/compare/main...fix-t5-compilation

the compiler args sent to the tracing API are: 
```
['--auto-cast', 'matmult', '--auto-cast-type', 'bf16', '--optlevel', '2', '--model-type', 'transformer']
```

but the compilation of t5 decoder still failed on gather:

```
~/optimum-neuron$ optimum-cli export neuron --model t5-small --task text2text-generation --batch_size 1 --sequence_length 18 --num_beams 4 --auto_cast matmul --auto_cast_type bf16 t5_small_neuron/
***** Compiling encoder *****
Using Neuron: --auto-cast matmul
Using Neuron: --auto-cast-type bf16
.
Compiler status PASS
[Compilation Time] 19.91 seconds.
***** Compiling decoder *****
Using Neuron: --auto-cast matmul
Using Neuron: --auto-cast-type bf16
/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/torch_neuronx/xla_impl/hlo_conversion.py:159: UserWarning: Received an input tensor that was unused. Tensor will be ignored. (index=2, shape=torch.Size([4, 18, 512]), dtype=torch.float32)
  warnings.warn(
2024-10-30 13:59:53.000715:  10342  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-10-30 13:59:53.000717:  10342  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/a1a83fb7-2ff9-44fe-8a28-3f0c5693a600/model.MODULE_17781393804758048124+d7517139.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/a1a83fb7-2ff9-44fe-8a28-3f0c5693a600/model.MODULE_17781393804758048124+d7517139.neff --verbose=35
.
Compiler status PASS
2024-10-30 13:59:55.000345:  10342  INFO ||NEURON_CACHE||: Compile cache path: /var/tmp/neuron-compile-cache
2024-10-30 13:59:55.000349:  10342  INFO ||NEURON_CC_WRAPPER||: Call compiler with cmd: neuronx-cc compile --target=trn1 --framework=XLA /tmp/ubuntu/neuroncc_compile_workdir/4e0bbec8-2eb3-43a7-b534-13f4c309b68f/model.MODULE_13321020961491912986+d7517139.hlo_module.pb --output /tmp/ubuntu/neuroncc_compile_workdir/4e0bbec8-2eb3-43a7-b534-13f4c309b68f/model.MODULE_13321020961491912986+d7517139.neff --verbose=35
.
Compiler status PASS
.root = neuronxcc/starfish/penguin/targets/sunda/passes/LegalizeSundaMacro.py
root = neuronxcc/starfish/penguin/targets/sunda/passes
root = neuronxcc/starfish/penguin/targets/sunda
root = neuronxcc/starfish/penguin/targets
root = neuronxcc/starfish/penguin
root = neuronxcc/starfish

[TEN404] (_gather.690) Internal tensorizer error: LegalizeSundaMacro:Incorrect partition ap! - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/optimum/exporters/neuron/__main__.py", line 749, in <module>
    main()
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/optimum/exporters/neuron/__main__.py", line 720, in main
    main_export(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/optimum/exporters/neuron/__main__.py", line 604, in main_export
    _, neuron_outputs = export_models(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/optimum/exporters/neuron/convert.py", line 368, in export_models
    neuron_inputs, neuron_outputs = export(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/optimum/exporters/neuron/convert.py", line 451, in export
    return export_neuronx(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/optimum/exporters/neuron/convert.py", line 581, in export_neuronx
    neuron_model = neuronx.trace(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 574, in trace
    neff_filename, metaneff, flattener, packer, weights = _trace(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 639, in _trace
    neff_artifacts = generate_neff(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 492, in generate_neff
    neff_filename = hlo_compile(
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/torch_neuronx/xla_impl/trace.py", line 394, in hlo_compile
    raise RuntimeError(f"neuronx-cc failed with {status}")
RuntimeError: neuronx-cc failed with 70
Traceback (most recent call last):
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/optimum/commands/optimum_cli.py", line 208, in main
    service.run()
  File "/home/ubuntu/pyvenv/aws_neuron_venv_2.20.1/lib/python3.8/site-packages/optimum/commands/export/neuronx.py", line 297, in run
    subprocess.run(full_command, shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 -m optimum.exporters.neuron --model t5-small --task text2text-generation --batch_size 1 --sequence_length 18 --num_beams 4 --auto_cast matmul --auto_cast_type bf16 t5_small_neuron/' returned non-zero exit status 1.
```

**Comment by JingyaHuang** [comment]
Sure:
```
absl-py==2.1.0
accelerate==0.29.2
aiohappyeyeballs==2.4.3
aiohttp==3.10.10
aiosignal==1.3.1
anyio==4.5.2
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
async-timeout==4.0.3
attrs==24.2.0
aws-neuronx-runtime-discovery==2.9
awscli==1.35.17
babel==2.16.0
backcall==0.2.0
beautifulsoup4==4.12.3
bleach==6.1.0
boto3==1.35.51
botocore==1.35.51
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
cloud-tpu-client==0.10
colorama==0.4.6
coloredlogs==15.0.1
comm==0.2.2
datasets==3.0.2
debugpy==1.8.7
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.8
docutils==0.16
ec2-metadata==2.13.0
environment-kernels==1.2.0
exceptiongroup==1.2.2
executing==2.1.0
fastjsonschema==2.20.0
filelock==3.16.1
fqdn==1.5.1
frozenlist==1.5.0
fsspec==2024.9.0
google-api-core==1.34.1
google-api-python-client==1.8.0
google-auth==2.35.0
google-auth-httplib2==0.2.0
googleapis-common-protos==1.65.0
h11==0.14.0
httpcore==1.0.6
httplib2==0.22.0
httpx==0.27.2
huggingface-hub==0.26.2
humanfriendly==10.0
idna==3.10
importlib_metadata==8.5.0
importlib_resources==6.4.5
ipykernel==6.29.5
ipython==8.12.3
ipywidgets==8.1.5
islpy==2023.2.5
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.4
jmespath==1.0.1
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter==1.1.1
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.2.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.13
libneuronxla==2.0.4986.0
lockfile==0.12.2
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mistune==3.0.2
ml-dtypes==0.2.0
mpmath==1.3.0
multidict==6.1.0
multiprocess==0.70.16
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==2.8.8
neuronx-cc==2.15.141.0+d3cfc8ca
notebook==7.2.2
notebook_shim==0.2.4
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.6.77
nvidia-nvtx-cu12==12.1.105
oauth2client==4.1.3
optimum==1.22.0
optimum-neuron @ file:///home/ubuntu/optimum-neuron
overrides==7.7.0
packaging==24.1
pandas==2.0.3
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
pgzip==0.3.5
pickleshare==0.7.5
pillow==10.4.0
pkg_resources==0.0.0
pkgutil_resolve_name==1.3.10
platformdirs==4.3.6
prometheus_client==0.21.0
prompt_toolkit==3.0.48
propcache==0.2.0
protobuf==3.20.3
psutil==6.1.0
ptyprocess==0.7.0
pure_eval==0.2.3
pyarrow==17.0.0
pyasn1==0.6.1
pyasn1_modules==0.4.1
pycparser==2.22
Pygments==2.18.0
pyparsing==3.1.4
python-daemon==3.1.0
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pytz==2024.2
PyYAML==6.0.2
pyzmq==26.2.0
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
requests-unixsocket==0.3.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.20.0
rsa==4.7.2
s3transfer==0.10.3
safetensors==0.4.5
scipy==1.10.1
Send2Trash==1.8.3
sentencepiece==0.2.0
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
stack-data==0.6.3
sympy==1.13.3
terminado==0.18.1
tinycss2==1.4.0
tokenizers==0.19.1
tomli==2.0.2
torch==2.1.2
torch-neuronx==2.1.2.2.3.1
torch-xla==2.1.4
torchvision==0.16.2
tornado==6.4.1
tqdm==4.66.6
traitlets==5.14.3
transformers==4.43.2
triton==2.1.0
types-python-dateutil==2.9.0.20241003
typing_extensions==4.12.2
tzdata==2024.2
uri-template==1.3.0
uritemplate==3.0.1
urllib3==1.26.20
wcwidth==0.2.13
webcolors==24.8.0
webencodings==0.5.1
websocket-client==1.8.0
wget==3.2
widgetsnbextension==4.0.13
xxhash==3.5.0
yarl==1.15.2
zipp==3.20.2
```

And it was tested with neuron sdk 2.20.1:

```
aws-neuronx-collectives/unknown,now 2.22.26.0-17a033bc8 amd64 [installed]
aws-neuronx-dkms/unknown,now 2.18.12.0 amd64 [installed]
aws-neuronx-runtime-lib/unknown,now 2.22.14.0-6e27b8d5b amd64 [installed]
aws-neuronx-tools/unknown,now 2.19.0.0 amd64 [installed]
```

**Comment by JingyaHuang** [comment]
Hi @aws-yishanm and @jeffhataws, Thanks for helping out. It turns out that the compilation error comes from both the "--model-type transformer" tag and the T5 decoder wrapper we added for tensor parallelism on the `reorder_cache` function. It seems to me that the tracing of `torch.index_select` has just failed since 2.20. 

I opened a PR in Optimum Neuron to patch this. Thanks for helping.
