### ISSUE TITLE
[TEN404] (_sine.127) Internal tensorizer error: BirCodeGenLoop:Too many strides!

### ISSUE THREAD

**Issue by bgalbraith** [aws-neuron/aws-neuron-sdk#1120]
Attempting to benchmark vLLM performance on NxDI (using the v0.6.x-neuron branch of https://github.com/aws-neuron/upstreaming-to-vllm.git per instructions)

Llama-3.1-8B and Llama-3.2-1B work fine, but Llama-3.2-3B produces the following error during compilation:

```
.......root = neuronxcc/starfish/penguin/targets/codegen/BirCodeGenLoop.py
root = neuronxcc/starfish/penguin/targets/codegen
root = neuronxcc/starfish/penguin/targets
root = neuronxcc/starfish/penguin
root = neuronxcc/starfish

[TEN404] (_sine.127) Internal tensorizer error: BirCodeGenLoop:Too many strides! {{{{0,+,1}[64],+,0}[2],+,64}[2],+,0}[2] - Please open a support ticket at https://github.com/aws-neuron/aws-neuron-sdk/issues/new. You may also be able to obtain more information using the 'XLA_IR_DEBUG' and 'XLA_HLO_DEBUG' environment variables.
Traceback (most recent call last):
  File "/home/ubuntu/upstreaming-to-vllm/benchmarks/benchmark_latency.py", line 269, in <module>
    main(args)
  File "/home/ubuntu/upstreaming-to-vllm/benchmarks/benchmark_latency.py", line 28, in main
    llm = LLM(
  File "/home/ubuntu/upstreaming-to-vllm/vllm/entrypoints/llm.py", line 214, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/home/ubuntu/upstreaming-to-vllm/vllm/engine/llm_engine.py", line 564, in from_engine_args
    engine = cls(
  File "/home/ubuntu/upstreaming-to-vllm/vllm/engine/llm_engine.py", line 325, in __init__
    self.model_executor = executor_class(
  File "/home/ubuntu/upstreaming-to-vllm/vllm/executor/executor_base.py", line 47, in __init__
    self._init_executor()
  File "/home/ubuntu/upstreaming-to-vllm/vllm/executor/neuron_executor.py", line 23, in _init_executor
    self._init_worker()
  File "/home/ubuntu/upstreaming-to-vllm/vllm/executor/neuron_executor.py", line 39, in _init_worker
    self.driver_worker.load_model()
  File "/home/ubuntu/upstreaming-to-vllm/vllm/worker/neuron_worker.py", line 134, in load_model
    self.model_runner.load_model()
  File "/home/ubuntu/upstreaming-to-vllm/vllm/worker/neuronx_distributed_model_runner.py", line 30, in load_model
    self.model = get_neuron_model(
  File "/home/ubuntu/upstreaming-to-vllm/vllm/model_executor/model_loader/neuronx_distributed.py", line 480, in get_neuron_model
    model.load_weights(model_config.model,
  File "/home/ubuntu/upstreaming-to-vllm/vllm/model_executor/model_loader/neuronx_distributed.py", line 150, in load_weights
    self.model.compile(compiled_model_path)
  File "/opt/aws_neuronx_venv_pytorch_2_5_nxd_inference/lib/python3.10/site-packages/neuronx_distributed_inference/models/application_base.py", line 145, in compile
    traced_model = self.get_builder(debug).trace(initialize_model_weights=False)
  File "/opt/aws_neuronx_venv_pytorch_2_5_nxd_inference/lib/python3.10/site-packages/neuronx_distributed/trace/model_builder.py", line 310, in trace
    key, bucket_rank, neff_artifacts = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/aws_neuronx_venv_pytorch_2_5_nxd_inference/lib/python3.10/site-packages/neuronx_distributed/trace/model_builder.py", line 254, in submit_compilation_job
    return key, bucket_rank, torch_neuronx.xla_impl.trace.generate_neff(*args)
  File "/opt/aws_neuronx_venv_pytorch_2_5_nxd_inference/lib/python3.10/site-packages/torch_neuronx/xla_impl/trace.py", line 506, in generate_neff
    neff_filename = hlo_compile(
  File "/opt/aws_neuronx_venv_pytorch_2_5_nxd_inference/lib/python3.10/site-packages/torch_neuronx/xla_impl/trace.py", line 396, in hlo_compile
    raise RuntimeError(f"neuronx-cc failed with {status}")
RuntimeError: neuronx-cc failed with 70
```

**Comment by aws-kingrj** [comment]
Hi, we will take a look and investigate

**Comment by sssrijan-amazon** [comment]
Hi @bgalbraith I tried to run `offline_inference_neuronx_distributed.py` [example script](https://github.com/aws-neuron/upstreaming-to-vllm/blob/v0.6.x-neuron/examples/offline_inference_neuronx_distributed.py) with llama-3.2-3B with the [Neuron 2.21.1 release](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#neuron-2-21-1-01-14-2025) artifacts and I was able to compile and serve the model.

Can you send the details about the neuron specific dependencies that you have in your environment (`pip list | grep neuron`) and also your script to start the vLLM server?

**Comment by bgalbraith** [comment]
Hi @sssrijan-amazon, thanks for taking a look. 

I'm using the UbuntuNeuron DLAMI on an inf2.8xlarge instance.
```
libneuronxla                      2.1.714.0
neuronx-cc                        2.16.372.0+4a9b2326
neuronx-distributed               0.10.1
neuronx-distributed-inference     0.1.1
torch-neuronx                     2.5.1.2.4.0
vllm                              0.1.dev2830+g22c56ee.neuron216 /home/ubuntu/upstreaming-to-vllm
```

As a quick test, I found I could recreate the error just using that same example script and the following change:
```
    max_model_len=1024,
    block_size=1024,
```
Llama-3.2-1B works fine, Llama-3.2-3B produces the above error.

**Comment by sssrijan-amazon** [comment]
Thanks for responding. I am able to replicate the issue on `Inf2.8xl` instance for `Llama-3.2-3B` with the offline inference script with the following changes.

```
max_model_len=1024,
block_size=1024,
tensor_parallel_size=2
```

On a side note, this works on `trn1.32xlarge` instance with `tensor_parallel_size=32`
We are further debugging the compilation error and will share an update when we've made progress debugging this.

**Comment by aws-yyjau** [comment]
Hi @bgalbraith 

Thanks for reporting this issue.
This should be fixed with the latest release (2.23): https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#id5

I'll close the issue for now.
Please let us know if it is still an issue. Thanks!
